Entity riding changes (#2221)
* (1/x) entity riding & inventory changes

* Move entity rider movement into Entity
* Move entity inventory opening into Entity (eg chestboat, horse)
* Allow custom entites to be controllable by their rider
* Deprecate EntityRideable

* undo npc test changes

* remove unused ItemFrameDropItemProcessor (deprecated since 1.16.210)

* update feat/riding to latest (#2222)

* Fix firework entity & stop motion when immobile (#2204)

* Add functions to send/clear debug shapes at player side

* oops

* add methods to update/remove debugshape

* Fix firework entity & stop motion when immobile

* Fixed head rotation on placement (#2208)

* Fixed that some blocks do not show after being generated (#2207)

* fix: TimeUnit constant casing in Gradle build (#2209)

* Fixed wrong enchantment ids in the named map (#2211)

* Added the working armor trim recipe (#2212)

* Fix/player close (#2206)

Fix player spawn NBT saving with proper provider null checks

- Added explicit null checks for level provider when saving spawn data
- Fallback to default level if spawn level provider is null
- Previously, on player logout the level object was non-null but its provider was null
- This caused the code to attempt saving with an invalid level, making the player appear not logged out and preventing their data from being saved

Fixes this issue;

17:42:13 [Netty Server IO #1] [INFO] EngincanErgunGG[/192.168.1.71:62829] logged in with entity id 1 at (island_0, 256.3727, 70.0, 253.4865)
17:42:37 [main] [INFO] Unloading level "island_0 //my task is unloaded island world
17:42:43 [DefaultDispatcher-worker-1] [INFO] Preparing level "island_0"
17:42:43 [DefaultDispatcher-worker-1] [INFO] Loading is complete for level "island_0" //i go to my island and place blocks etc. after i go to world
17:43:17 [main] [INFO] Unloading level "island_0 //my task is unloaded island world
17:43:23 [Netty Server IO #1] [INFO] EngincanErgunGG[/192.168.1.71:62829] logged out due to disconnect.disconnected
> player disconnected world is: world //quit event log
17:43:23 [Netty Server IO #1] [ERROR] Exception whilst closing session
cn.nukkit.utils.LevelException: The level "C:\Users\PC\Desktop\Skyblock\worlds\island_0" is already closed (have no providers)
        at cn.nukkit.level.Level.requireProvider(Level.java:628) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getName(Level.java:4396) ~[powernukkitx.jar:?]
        at cn.nukkit.Player.saveNBT(Player.java:3556) ~[powernukkitx.jar:?]

* Fixed that water flows though the full side of stairs (#2214)

* Fixed frostwalker (#2213)

* Merged reload to debug command (#2210)

Merged reload to debug command
Added PluginReloadEvent and ServerReloadEvent
Merged plugin reload function to PluginManager#reloadPlugin

* Fixed player kick event (#2220)

---------

Co-authored-by: Buddelbubi <44944269+Buddelbubi@users.noreply.github.com>
Co-authored-by: xRookieFight <me@xrookiefight.com>
Co-authored-by: EngincanErgunGG <77359402+EngincanErgunGG@users.noreply.github.com>
Co-authored-by: Semih Akın <90553714+SemihAkin685@users.noreply.github.com>

* Fix null check for riding entity before dismounting

* Update link from powernukkitx.com to powernukkitx.org

* update feat/riding (#2224)

* Fix firework entity & stop motion when immobile (#2204)

* Add functions to send/clear debug shapes at player side

* oops

* add methods to update/remove debugshape

* Fix firework entity & stop motion when immobile

* Fixed head rotation on placement (#2208)

* Fixed that some blocks do not show after being generated (#2207)

* fix: TimeUnit constant casing in Gradle build (#2209)

* Fixed wrong enchantment ids in the named map (#2211)

* Added the working armor trim recipe (#2212)

* Fix/player close (#2206)

Fix player spawn NBT saving with proper provider null checks

- Added explicit null checks for level provider when saving spawn data
- Fallback to default level if spawn level provider is null
- Previously, on player logout the level object was non-null but its provider was null
- This caused the code to attempt saving with an invalid level, making the player appear not logged out and preventing their data from being saved

Fixes this issue;

17:42:13 [Netty Server IO #1] [INFO] EngincanErgunGG[/192.168.1.71:62829] logged in with entity id 1 at (island_0, 256.3727, 70.0, 253.4865)
17:42:37 [main] [INFO] Unloading level "island_0 //my task is unloaded island world
17:42:43 [DefaultDispatcher-worker-1] [INFO] Preparing level "island_0"
17:42:43 [DefaultDispatcher-worker-1] [INFO] Loading is complete for level "island_0" //i go to my island and place blocks etc. after i go to world
17:43:17 [main] [INFO] Unloading level "island_0 //my task is unloaded island world
17:43:23 [Netty Server IO #1] [INFO] EngincanErgunGG[/192.168.1.71:62829] logged out due to disconnect.disconnected
> player disconnected world is: world //quit event log
17:43:23 [Netty Server IO #1] [ERROR] Exception whilst closing session
cn.nukkit.utils.LevelException: The level "C:\Users\PC\Desktop\Skyblock\worlds\island_0" is already closed (have no providers)
        at cn.nukkit.level.Level.requireProvider(Level.java:628) ~[powernukkitx.jar:?]
        at cn.nukkit.level.Level.getName(Level.java:4396) ~[powernukkitx.jar:?]
        at cn.nukkit.Player.saveNBT(Player.java:3556) ~[powernukkitx.jar:?]

* Fixed that water flows though the full side of stairs (#2214)

* Fixed frostwalker (#2213)

* Merged reload to debug command (#2210)

Merged reload to debug command
Added PluginReloadEvent and ServerReloadEvent
Merged plugin reload function to PluginManager#reloadPlugin

* Fixed player kick event (#2220)

* fix: Mob spawners (#2216)

* Fixed that mobs still spawn when disabled with torches

* Fixed that spawner with nbt does not spawn with mob

* Removed unused imports

* Fixed frosted ice decay (#2223)

---------

Co-authored-by: Buddelbubi <44944269+Buddelbubi@users.noreply.github.com>
Co-authored-by: xRookieFight <me@xrookiefight.com>
Co-authored-by: EngincanErgunGG <77359402+EngincanErgunGG@users.noreply.github.com>
Co-authored-by: Semih Akın <90553714+SemihAkin685@users.noreply.github.com>

* Make use of new riding input method, make boat & minecart collideable

---------

Co-authored-by: Buddelbubi <44944269+Buddelbubi@users.noreply.github.com>
Co-authored-by: xRookieFight <me@xrookiefight.com>
Co-authored-by: EngincanErgunGG <77359402+EngincanErgunGG@users.noreply.github.com>
Co-authored-by: Semih Akın <90553714+SemihAkin685@users.noreply.github.com>